// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: account.sql

package db

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO account (
  owner, 
  balance,
  currencry
) VALUES (
  $1, $2, $3
)  RETURNING id_account, owner, balance, currencry, created_at
`

type CreateAccountParams struct {
	Owner     int32  `json:"owner"`
	Balance   string `json:"balance"`
	Currencry string `json:"currencry"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount, arg.Owner, arg.Balance, arg.Currencry)
	var i Account
	err := row.Scan(
		&i.IDAccount,
		&i.Owner,
		&i.Balance,
		&i.Currencry,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM account WHERE id_account = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, idAccount int64) error {
	_, err := q.db.ExecContext(ctx, deleteAccount, idAccount)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id_account, owner, balance, currencry, created_at FROM account
WHERE id_account = $1 LIMIT 1
`

func (q *Queries) GetAccount(ctx context.Context, idAccount int64) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, idAccount)
	var i Account
	err := row.Scan(
		&i.IDAccount,
		&i.Owner,
		&i.Balance,
		&i.Currencry,
		&i.CreatedAt,
	)
	return i, err
}

const listAccount = `-- name: ListAccount :many
SELECT id_account, owner, balance, currencry, created_at FROM account
ORDER BY id_account LIMIT $1 OFFSET $2
`

type ListAccountParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAccount(ctx context.Context, arg ListAccountParams) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccount, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.IDAccount,
			&i.Owner,
			&i.Balance,
			&i.Currencry,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE account SET balance = $2
WHERE id_account = $1
RETURNING id_account, owner, balance, currencry, created_at
`

type UpdateAccountParams struct {
	IDAccount int64  `json:"id_account"`
	Balance   string `json:"balance"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, updateAccount, arg.IDAccount, arg.Balance)
	var i Account
	err := row.Scan(
		&i.IDAccount,
		&i.Owner,
		&i.Balance,
		&i.Currencry,
		&i.CreatedAt,
	)
	return i, err
}
