// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	IDAccount int64     `json:"id_account"`
	Owner     int32     `json:"owner"`
	Balance   string    `json:"balance"`
	Currencry string    `json:"currencry"`
	CreatedAt time.Time `json:"created_at"`
}

type Entry struct {
	IDEntries int64         `json:"id_entries"`
	AccountID sql.NullInt64 `json:"account_id"`
	Amount    int64         `json:"amount"`
	CreatedAt time.Time     `json:"created_at"`
}

type Transfer struct {
	IDTransfer    int64         `json:"id_transfer"`
	FromAccountID sql.NullInt64 `json:"from_account_id"`
	ToAccountID   sql.NullInt64 `json:"to_account_id"`
	Amount        int64         `json:"amount"`
	CreatedAt     time.Time     `json:"created_at"`
}
