// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: transfer.sql

package db

import (
	"context"
	"database/sql"
)

const createTransfer = `-- name: CreateTransfer :one
INSERT INTO transfer (
  from_account_id, 
  to_account_id,
  amount
) VALUES (
  $1, $2, $3
)  RETURNING id_transfer, from_account_id, to_account_id, amount, created_at
`

type CreateTransferParams struct {
	FromAccountID sql.NullInt64 `json:"from_account_id"`
	ToAccountID   sql.NullInt64 `json:"to_account_id"`
	Amount        int64         `json:"amount"`
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, createTransfer, arg.FromAccountID, arg.ToAccountID, arg.Amount)
	var i Transfer
	err := row.Scan(
		&i.IDTransfer,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTransfer = `-- name: DeleteTransfer :exec
DELETE FROM transfer WHERE id_transfer = $1
`

func (q *Queries) DeleteTransfer(ctx context.Context, idTransfer int64) error {
	_, err := q.db.ExecContext(ctx, deleteTransfer, idTransfer)
	return err
}

const getTransfer = `-- name: GetTransfer :one
SELECT id_transfer, from_account_id, to_account_id, amount, created_at FROM transfer
WHERE id_transfer = $1 LIMIT 1
`

func (q *Queries) GetTransfer(ctx context.Context, idTransfer int64) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, getTransfer, idTransfer)
	var i Transfer
	err := row.Scan(
		&i.IDTransfer,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const listTransfer = `-- name: ListTransfer :many
SELECT id_transfer, from_account_id, to_account_id, amount, created_at FROM transfer
ORDER BY id_transfer LIMIT $1 OFFSET $2
`

type ListTransferParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTransfer(ctx context.Context, arg ListTransferParams) ([]Transfer, error) {
	rows, err := q.db.QueryContext(ctx, listTransfer, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transfer
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.IDTransfer,
			&i.FromAccountID,
			&i.ToAccountID,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransfer = `-- name: UpdateTransfer :one
UPDATE transfer SET amount = $2
WHERE id_transfer = $1
RETURNING id_transfer, from_account_id, to_account_id, amount, created_at
`

type UpdateTransferParams struct {
	IDTransfer int64 `json:"id_transfer"`
	Amount     int64 `json:"amount"`
}

func (q *Queries) UpdateTransfer(ctx context.Context, arg UpdateTransferParams) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, updateTransfer, arg.IDTransfer, arg.Amount)
	var i Transfer
	err := row.Scan(
		&i.IDTransfer,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}
